name: 'Github Issue Creator'
description: 'This action creates an issue based on user inputs'
author: 'Thomas Joseph'

inputs:
  GITHUB_TOKEN:
    description: "Token for authenticating GitHub API"
    required: true
  INPUT_TITLE:
    description: "Title of the issue"
    required: true
  INPUT_BODY:
    description: "Body of the issue"
    required: false
    default: ""
  INPUT_LABELS:
    description: "Comma-separated list of labels"
    required: false
    default: ""
  INPUT_ASSIGNEES:
    description: "Comma-separated list of assignees"
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'

# for publishing purposes
branding: #generates a logo for our action
  icon: arrow-down #icon of the image
  color: green # background color of the logo of our action